document.addEventListener('DOMContentLoaded', function() {
    // The path to the results file generated by the workflow
    const dataUrl = 'dashboard_data.json';

    fetch(dataUrl)
        .then(response => response.json())
        .then(data => {
            // Update stats
            document.getElementById('total-targets').textContent = data.summary.total_targets;
            document.getElementById('critical-findings').textContent = data.summary.critical_findings_count;
            document.getElementById('last-update').textContent = new Date(data.summary.last_update).toLocaleString();

            // Populate table
            const tableBody = document.querySelector('#results-table tbody');
            data.results.forEach(result => {
                const row = document.createElement('tr');
                    
                let statusClass = 'status-ok';
                if (result.status === 'critical') {
                    statusClass = 'status-critical';
                }

                row.innerHTML = `
                    <td>${result.target}</td>
                    <td>${result.ai_summary}</td>
                    <td class="${statusClass}">${result.status}</td>
                `;
                tableBody.appendChild(row);
            });
        })
        .catch(error => {
            console.error('Error loading dashboard data:', error);
            const tableBody = document.querySelector('#results-table tbody');
            tableBody.innerHTML = `<tr><td colspan="3">Could not load data. Run the 'Olympus Engine' workflow to generate it.</td></tr>`;
        });
});
